[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.googletagmanager.com https://*.google-analytics.com https://*.googleapis.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https: http:;
      font-src 'self' data:;
      connect-src 'self' https://*.googleapis.com https://*.google-analytics.com https://firebase.googleapis.com https://*.firebaseio.com wss://*.firebaseio.com;
      frame-src 'self' https://*.firebaseapp.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      media-src 'self' data:;
      worker-src 'self' blob:;
      """
